### ISSUE TITLE
Error [ERR_HTTP2_GOAWAY_SESSION]: New streams cannot be created after receiving a GOAWAY

### ISSUE THREAD

**Issue by franz-liszt** [hisco/http2-client#3]
```
Error [ERR_HTTP2_GOAWAY_SESSION]: New streams cannot be created after receiving a GOAWAY
at ClientHttp2Session.request (internal/http2/core.js:1361:13)
at HttpsRequest.makeHttp2Request (http2-client/lib/request.js:412:30)
at HttpsRequest.makeRequest (http2-client/lib/request.js:344:21)
at HttpsRequest.onMakeRequest (http2-client/lib/request.js:274:24)
at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
at process._tickCallback (internal/process/next_tick.js:61:11)
```
Let me know if you need more information
Thanks

**Comment by hisco** [comment]
Thank you for reaching out!
Fixed in #4 and available on npm latest.
